apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.podname}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.podname}}
  template:
    metadata:
      labels:
        app: {{.Values.image}}
    spec:
      containers:
      - name: container
        image: parks4754/{{.Values.containername}}
        ports:
        - containerPort: 80
        
        resources:
          requests:
            cpu: 100m
            memory: 500Mi

